events {
    worker_connections 1024;  # Defines the maximum number of simultaneous connections each worker can handle
}

http {    
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate_key /etc/letsencrypt/live/test.williamcwx.com/privkey.pem;      
        ssl_certificate /etc/letsencrypt/live/test.williamcwx.com/fullchain.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:EECDH+AESGCM:EDH+AESGCM';
        ssl_prefer_server_ciphers on;

        # for godot
        add_header Cross-Origin-Embedder-Policy "require-corp";
        add_header Cross-Origin-Opener-Policy "same-origin";

        location / {
            proxy_pass http://nodejs-app:3000;
        }
    }

    server {
        listen 80;
        server_name localhost;

        return 301 https://$host$request_uri;
    }
}